### ISSUE TITLE
[Indexer] Milestone 1 delivery

### ISSUE THREAD

**Issue by veigajoao** [hack-a-chain-software/indexer-kadena#8]
- [x] Connect data streaming to project
- [x] Add node creation to Terraform
- [x] Create devops pipeline
- [x] Save sync status to database
- [x] Save sync error to database
- [x] Change backfill to fill
- [x] Add telemetry 
- [x] Retry errors
- [x] Add missing blocks check
- [ ] Run full sync
- [ ] Add tests
